//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PubSubService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEASUREMENT
    {
        public int ID { get; set; }
        public decimal VALUE { get; set; }
        public string STATION_ID { get; set; }
        public string TYPE { get; set; }
        public System.DateTime TIME { get; set; }
    
        public virtual STATION STATION { get; set; }
    }
}
