//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PubSubService
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STATIONS()
        {
            this.MEASUREMENTS = new HashSet<MEASUREMENTS>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public int LOCATION_ID { get; set; }
    
        public virtual LOCATIONS LOCATIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEASUREMENTS> MEASUREMENTS { get; set; }
    }
}
